<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'CodingMs\\AdditionalTca\\' => array($typo3InstallDir . 'typo3conf/ext/additional_tca/Classes'),
    'CodingMs\\Calendars\\' => array($typo3InstallDir . 'typo3conf/ext/calendars/Classes'),
    'CodingMs\\InfoniqaJobs\\' => array($typo3InstallDir . 'typo3conf/ext/infoniqa_jobs/Classes'),
    'EconcessGmbh\\BootstrapPackageEconcess\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package_econcess/Classes'),
    'Econcess\\NewsSections\\' => array($typo3InstallDir . 'typo3conf/ext/ec_news_sections/Classes'),
    'Econcess\\PageSpeed\\' => array($typo3InstallDir . 'typo3conf/ext/ec_page_speed/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'GeorgRinger\\NumberedPagination\\' => array($typo3InstallDir . 'typo3conf/ext/numbered_pagination/Classes'),
    'Mediadreams\\MdNewsAuthor\\' => array($typo3InstallDir . 'typo3conf/ext/md_news_author/Classes'),
    'Mwwebinare\\Mwwebinare\\' => array($typo3InstallDir . 'typo3conf/ext/mwwebinare/Classes'),
    'SpecialistaWeb\\Newsstylist\\' => array($typo3InstallDir . 'typo3conf/ext/newsstylist/Classes'),
    'TYPO3\\CMS\\Introduction\\' => array($typo3InstallDir . 'typo3conf/ext/introduction/Classes'),
);
